apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: eduardopetrini/k8s-cronjob:latest
            imagePullPolicy: Never
          restartPolicy: OnFailure
