apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata: 
      labels:
        server: k8s-cronjob
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: {{ .Values.k8sCronjob.image.name }}:{{ .Values.k8sCronjob.image.tag }}
            imagePullPolicy: Never
          restartPolicy: OnFailure
